//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.BranchAddresses = new HashSet<BranchAddress>();
            this.CompanyFiles = new HashSet<CompanyFile>();
            this.CompanyLangs = new HashSet<CompanyLang>();
            this.CompanyTypeOfWorks = new HashSet<CompanyTypeOfWork>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string WebSite { get; set; }
        public string Introduction { get; set; }
        public int NumberOfEmployees { get; set; }
        public byte YearsOfExperience { get; set; }
        public bool LiabilityInsurance { get; set; }
        public Nullable<decimal> LiabilityInsuranceAmount { get; set; }
        public string AgreeTermsAndCondition { get; set; }
        public string LegalRight { get; set; }
        public byte[] ElectroniceSignature { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BranchAddress> BranchAddresses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyFile> CompanyFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyLang> CompanyLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyTypeOfWork> CompanyTypeOfWorks { get; set; }
    }
}
