//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GuardRequest()
        {
            this.GuardRequestTypeOfWorks = new HashSet<GuardRequestTypeOfWork>();
            this.JobPostings = new HashSet<JobPosting>();
            this.NotificationQueues = new HashSet<NotificationQueue>();
        }
    
        public int Id { get; set; }
        public Nullable<int> TypeOfServiceId { get; set; }
        public Nullable<int> TypeOfPositionId { get; set; }
        public Nullable<int> BranchAddressId { get; set; }
        public Nullable<int> StaffTeamId { get; set; }
        public string Description { get; set; }
        public string SpecialRemark { get; set; }
        public string ServiceLocation { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsResponded { get; set; }
        public string AspNetUsersId { get; set; }
        public string RespondedByAspNetUsersId { get; set; }
    
        public virtual BranchAddress BranchAddress { get; set; }
        public virtual StaffTeam StaffTeam { get; set; }
        public virtual TypeOfPosition TypeOfPosition { get; set; }
        public virtual TypeOfService TypeOfService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuardRequestTypeOfWork> GuardRequestTypeOfWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPosting> JobPostings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationQueue> NotificationQueues { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
