//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobApply
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobApply()
        {
            this.JobHires = new HashSet<JobHire>();
        }
    
        public int Id { get; set; }
        public int JobPostingId { get; set; }
        public int JobSeekerId { get; set; }
        public int JobApplyStatusId { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public System.DateTime AppliedDate { get; set; }
    
        public virtual JobApplyStatu JobApplyStatu { get; set; }
        public virtual JobPosting JobPosting { get; set; }
        public virtual JobSeeker JobSeeker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobHire> JobHires { get; set; }
    }
}
