//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobPosting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobPosting()
        {
            this.JobApplies = new HashSet<JobApply>();
            this.JobPostingFiles = new HashSet<JobPostingFile>();
            this.JobPostingTypeOfWorks = new HashSet<JobPostingTypeOfWork>();
            this.NotificationQueues = new HashSet<NotificationQueue>();
        }
    
        public int Id { get; set; }
        public string JobId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> GuardRequestId { get; set; }
        public Nullable<int> TypeOfPositionId { get; set; }
        public Nullable<int> BranchAddressId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<int> EducationLevelId { get; set; }
        public Nullable<int> TypeOfServiceId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsExpired { get; set; }
        public Nullable<System.DateTime> ExpiryDue { get; set; }
        public Nullable<System.DateTime> ExpiredDate { get; set; }
        public Nullable<bool> IsHired { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteReason { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string AspNetUsersId { get; set; }
        public string DeleteAspNetUsersId { get; set; }
    
        public virtual BranchAddress BranchAddress { get; set; }
        public virtual city city { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual GuardRequest GuardRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApply> JobApplies { get; set; }
        public virtual TypeOfPosition TypeOfPosition { get; set; }
        public virtual TypeOfService TypeOfService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPostingFile> JobPostingFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobPostingTypeOfWork> JobPostingTypeOfWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationQueue> NotificationQueues { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
