//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeekerFile
    {
        public int Id { get; set; }
        public int JobSeekerId { get; set; }
        public string ResumeFilePath { get; set; }
        public string ResumeText { get; set; }
        public string CPRFirstAidCertificateFilePath { get; set; }
        public string SecurityLicenseCertificateFilePath { get; set; }
        public string EligibilityFilePath { get; set; }
        public string EducationFilePath { get; set; }
        public string PhotoPath { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
