//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeeker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobSeeker()
        {
            this.JobAlerts = new HashSet<JobAlert>();
            this.JobApplies = new HashSet<JobApply>();
            this.JobSeekerContactLogs = new HashSet<JobSeekerContactLog>();
            this.JobSeekerFiles = new HashSet<JobSeekerFile>();
            this.JobSeekerLangs = new HashSet<JobSeekerLang>();
            this.JobSeekerScores = new HashSet<JobSeekerScore>();
            this.JobSeekerSecurityExperiences = new HashSet<JobSeekerSecurityExperience>();
            this.JobSeekerTypeOfWorks = new HashSet<JobSeekerTypeOfWork>();
            this.JobSeekerTypeOfWorkAvailabilities = new HashSet<JobSeekerTypeOfWorkAvailability>();
            this.References = new HashSet<Reference>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Address { get; set; }
        public string PostalCode { get; set; }
        public string CellPhone { get; set; }
        public string HomePhone { get; set; }
        public string OfficePhone { get; set; }
        public int EducationLevelId { get; set; }
        public string OtherEduction { get; set; }
        public Nullable<bool> IsWillingToBeTrained { get; set; }
        public bool HasCar { get; set; }
        public byte YearsOfExperience { get; set; }
        public Nullable<bool> WillProvidereference { get; set; }
        public int JobSeekerStatusId { get; set; }
        public int TypeOfServiceId { get; set; }
        public Nullable<decimal> RateDesiredPerHour { get; set; }
        public Nullable<bool> BenefitDesired { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public bool HasSecurityLicense { get; set; }
        public Nullable<System.DateTime> SecurityLicenseExpiry { get; set; }
        public Nullable<bool> IsShiftAvailable { get; set; }
        public Nullable<int> TypeOfNoticeId { get; set; }
        public string AnotherLanguage { get; set; }
        public Nullable<bool> HasValidFirstAidCertificate { get; set; }
        public Nullable<bool> HasLawSecurityCommunityCollegeCertificate { get; set; }
        public Nullable<bool> IsCurrentlyWorking { get; set; }
        public Nullable<System.DateTime> WorkPermitExpiry { get; set; }
        public string AspNetUsersId { get; set; }
        public Nullable<int> DefaultCityId { get; set; }
        public Nullable<bool> IsCurrentlyHire { get; set; }
    
        public virtual EducationLevel EducationLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobAlert> JobAlerts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApply> JobApplies { get; set; }
        public virtual JobSeekerStatu JobSeekerStatu { get; set; }
        public virtual TypeOfJobNotice TypeOfJobNotice { get; set; }
        public virtual TypeOfService TypeOfService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeekerContactLog> JobSeekerContactLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeekerFile> JobSeekerFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeekerLang> JobSeekerLangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeekerScore> JobSeekerScores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeekerSecurityExperience> JobSeekerSecurityExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeekerTypeOfWork> JobSeekerTypeOfWorks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeekerTypeOfWorkAvailability> JobSeekerTypeOfWorkAvailabilities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reference> References { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual city city { get; set; }
    }
}
