//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobSeekerScore
    {
        public int Id { get; set; }
        public int JobSeekerId { get; set; }
        public Nullable<int> SecurityGuardExp { get; set; }
        public Nullable<int> SecurityGuardLicense { get; set; }
        public Nullable<int> ValidAidCertificate { get; set; }
        public Nullable<int> SecurityCommunityCollegeCertificate { get; set; }
        public Nullable<int> PoliceMilitaryExp { get; set; }
        public Nullable<int> DriverLicense { get; set; }
        public Nullable<int> HaveVehicle { get; set; }
        public Nullable<int> FluenInEnglish { get; set; }
        public Nullable<int> ExperienceMSOffice { get; set; }
        public Nullable<int> AvailableAllShift { get; set; }
        public Nullable<int> CurrentlyWorking { get; set; }
        public Nullable<int> ServiceTypeDesired { get; set; }
        public Nullable<int> ResumeAttached { get; set; }
        public Nullable<int> Extra { get; set; }
        public string ExtraDescription { get; set; }
        public Nullable<int> TotalScore { get; set; }
    
        public virtual JobSeeker JobSeeker { get; set; }
    }
}
