//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationQueue
    {
        public int Id { get; set; }
        public int NotificationStatusTypeId { get; set; }
        public string EmailTo { get; set; }
        public string EmailFrom { get; set; }
        public string EmailCC { get; set; }
        public int NotificationTypeId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public Nullable<bool> IsBodyHTML { get; set; }
        public byte NumberOfAttempt { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> JobPostingId { get; set; }
        public Nullable<int> JobAlertId { get; set; }
        public Nullable<int> GuardRequestId { get; set; }
        public string AttachmentFile { get; set; }
        public string AspNetUsersId { get; set; }
        public string ExceptionMessage { get; set; }
        public Nullable<System.DateTime> ExceptionDate { get; set; }
    
        public virtual GuardRequest GuardRequest { get; set; }
        public virtual JobAlert JobAlert { get; set; }
        public virtual JobPosting JobPosting { get; set; }
        public virtual NotificationType NotificationType { get; set; }
        public virtual TypeOfNotificationStatu TypeOfNotificationStatu { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
