//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteConfig
    {
        public int Id { get; set; }
        public int MinNumberOfBiddable { get; set; }
        public byte NumberOfProvider { get; set; }
        public int MaxNumberOfActiveRequest { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int SecondOfNotificationMonitor { get; set; }
        public bool MonitorSwitch { get; set; }
        public int HourOfSchedule { get; set; }
        public bool ScheduleSwitch { get; set; }
        public Nullable<decimal> HSTPercentage { get; set; }
    }
}
