//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitingPortal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeOfSecurityExperience
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TypeOfSecurityExperience()
        {
            this.JobSeekerSecurityExperiences = new HashSet<JobSeekerSecurityExperience>();
            this.TypeOfSecurityExperience1 = new HashSet<TypeOfSecurityExperience>();
        }
    
        public int Id { get; set; }
        public Nullable<int> SubId { get; set; }
        public string Name { get; set; }
        public int Seq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSeekerSecurityExperience> JobSeekerSecurityExperiences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TypeOfSecurityExperience> TypeOfSecurityExperience1 { get; set; }
        public virtual TypeOfSecurityExperience TypeOfSecurityExperience2 { get; set; }
    }
}
